### ISSUE TITLE
Branch 12.0-RELEASE does not exist at https://github.com/freenas/iocage-ix-plugins.git!

### ISSUE THREAD

**Issue by atomicbeecz** [freenas/iocage-ix-plugins#73]
Problem: getting traceback, when trying to list available plugins for 12.0-RELEASE 
ideally not return traceback, but some normal error message or something. (like "no plugins available for release 12.0-RELEASE)

root@testbsd:~ # iocage list -r
+---------------+
| Bases fetched |
+===============+
| 12.0-RELEASE  |
+---------------+

root@testbsd:~ # iocage list --plugins --remote

Branch 12.0-RELEASE does not exist at https://github.com/freenas/iocage-ix-plugins.git!
Using "master" branch for plugin, this may not work with your RELEASE
Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage_cli/list.py", line 99, in cli
    ioc_common.logit({"level": "INFO", "message": _list})
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/ioc_common.py", line 99, in logit
    _callback(content, exception)
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/ioc_common.py", line 56, in callback
    log.info(message)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 1308, in info
    self._log(INFO, msg, args, **kwargs)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 1444, in _log
    self.handle(record)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 1454, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 1516, in callHandlers
    hdlr.handle(record)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 865, in handle
    self.emit(record)
  File "/usr/local/lib/python3.6/site-packages/iocage_cli/__init__.py", line 76, in emit
    print(log, file=sys.stdout)
UnicodeEncodeError: 'ascii' codec can't encode character '\u2122' in position 1815: ordinal not in range(128)
root@testbsd:~ #

**Comment by skarekrow** [comment]
Is this in freenas? Otherwise update to the latest iocage master as this was fixed in https://github.com/iocage/iocage/commit/0744c943df387af248e412d0588fb22b3760b15c and https://github.com/iocage/iocage/commit/f29685076e3f75a7bee70f21589d05eb923e3f51

**Comment by atomicbeecz** [comment]
aha, ok, then close this case pls. (it's not in freenas)
